# Generated by Django 5.1.4 on 2025-01-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_user_weeklytimelimithours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
